services:
  api:
    build:
      context: .
      dockerfile: code/deployment/api/Dockerfile
    ports:
      - "8001:8000"

  app:
    build:
      context: .
      dockerfile: code/deployment/app/Dockerfile
    ports:
      - "8502:8501"
    depends_on:
      - api
